# Generated by Django 6.0 on 2026-01-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_subtitle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit of Measure'),
        ),
    ]
